### ISSUE TITLE
Error: INSTALLATION FAILED

### ISSUE THREAD

**Issue by CrushCCD** [liuxuzxx/csi-s3#10]
helm install csi-s3 ./ -n default
Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728
[root@localhost s3-csi]#

我想请问一下这个问题怎么解决  我尝试修改了k3s 的apiservice和拆分helm下的文件进行安装

**Comment by liuxuzxx** [comment]
看这个错误日志： 3145728  好像是3MB的大小限制 我需要检查下是否真的大于3MB了，我感觉应该不至于那么大吧？

**Comment by liuxuzxx** [comment]
我本地统计了下大小，获取到的数据如下:
```bash
56K	./csi-s3
60K	./
```

就是这个chart才56KB，距离3MB的阈值早着来

**Comment by CrushCCD** [comment]
> 我在本地统计了下大小，获取到的数据如下：
> 
> ```shell
> 56K	./csi-s3
> 60K	./
> ```
> 
> 就是这个图表才56KB，距离3MB的阈值早着来

我删除了我放置的文件，可以了  感谢

**Comment by liuxuzxx** [comment]
Ok
