### ISSUE TITLE
咨询一下如何支持多个namespace下安装

### ISSUE THREAD

**Issue by lingpony** [liuxuzxx/csi-s3#14]
咨询一下如何支持多个namespace下安装
helm install csi-s3 ./ -n xxx
ClusterRole、ClusterRoleBinding都已经存在
是否需要挨个修改yaml文件，有没有更好的方式

**Comment by liuxuzxx** [comment]
这个在多个namespace下安装，是同一个k8s集群下的不同namespace?

StorageClass这个资源对象是没有命名空间限制的，一个k8s集群内所有namespace下的pod都可以使用同一个StorageClass.

这种需要安装多个的原因和需求方便描述下吗？

**Comment by lingpony** [comment]
我看安装文件中Deployment的csi-s3-driver和DaemonSet的csi-s3-daemonset都是在namespace下的。这些是部署在default namespace？还是每个namespace都要部署一套

**Comment by lingpony** [comment]
我已经搞明白了，装在default下就可以全局使用了

**Comment by liuxuzxx** [comment]
其实不区分namespace的，主要是这些daemonset是要挂载在node机器上的

**Comment by liuxuzxx** [comment]
这个是StorageClass的资源信息
```bash
storageclasses                     sc                                     storage.k8s.io/v1                      false(是否是namespace级别的意思，false:不是)        StorageClass
```

**Comment by liuxuzxx** [comment]
其实，k8s的sc的使用大致都是：
1. 你的pod引用了sc，然后k8s的存储插件帮你创建一个pvc(当然可以直接挂载一个已经存在的pvc)
2. 接着，在k8s启动pod的时候，执行了mount -s挂载操作，挂载到本地的/var/pod/xxx/xxx/xx的一个目录
3. 然后存储插件，就使用node机器的rclone等程序执行mount操作，
4. 接着你的程序写到本地目录，rclone帮忙同步到远程的存储

其实就和你在一台机器启动一个进程，然后向通过nfs来把数据写道远程的nfs服务上.
1. 第一步，肯定是执行mount操作到nfs的某个目录上，假设本地目录是：/data/nfs
2. 接着你的程序使用本地的这个目录 /data/nfs，就可以了
3. 但是执行mount nfs的前提是，你的这个机器上需要安装nfs-utils依赖  daemonset就是做这个的。又因为daemonset需要提供namespace，所以，你会看到这个daemonset具体到某个命名空间了

**Comment by lingpony** [comment]
你好，不好意思，再咨询个问题
容器中文件系统权限、用户和s3的权限之间的关系是什么
我现在容器中的非root用户无法对s3的pv进行访问，这个/usr/share/nginx/html是pv挂载的目录，操作系统上看权限是root，现在想非root用户访问，权限都不能修改
------------------------------------------------------------------
发件人：刘旭 ***@***.***>
发送时间：2024年10月25日(星期五) 11:24
***@***.***>
***@***.***>; State ***@***.***>
主　题：Re: [liuxuzxx/csi-s3] 咨询一下如何支持多个namespace下安装 (Issue #14)
其实，k8s的sc的使用大致都是：

 * 
你的pod引用了sc，然后k8s的存储插件帮你创建一个pvc(当然可以直接挂载一个已经存在的pvc)

 * 
接着，在k8s启动pod的时候，执行了mount -s挂载操作，挂载到本地的/var/pod/xxx/xxx/xx的一个目录

 * 
然后存储插件，就使用node机器的rclone等程序执行mount操作，

 * 
接着你的程序写到本地目录，rclone帮忙同步到远程的存储
其实就和你在一台机器启动一个进程，然后向通过nfs来把数据写道远程的nfs服务上.

 * 
第一步，肯定是执行mount操作到nfs的某个目录上，假设本地目录是：/data/nfs

 * 
接着你的程序使用本地的这个目录 /data/nfs，就可以了

 * 
但是执行mount nfs的前提是，你的这个机器上需要安装nfs-utils依赖 daemonset就是做这个的。又因为daemonset需要提供namespace，所以，你会看到这个daemonset具体到某个命名空间了
